name: fleamarket
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  http: ^0.11.3+16
  json_serializable: ^0.5.0
  build_runner: ^0.8.7
  cupertino_icons: ^0.1.0
  intl: ^0.15.6
  image_picker: ^0.4.4
  carousel: ^0.1.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.






dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/startscreen.jpg
    - images/start.jpg
    - images/goods1.jpg
    - images/goods2.jpg
    - images/goods03.jpg
    - images/goods4.jpg
    - images/goods5.png
    - images/goods6.jpg
    - images/goods7.jpg
    - images/goods8.jpg
    - images/goods9.jpg
    - images/goods10.jpg
    - images/logo.png
    - images/profile.jpg
    - images/profileimage.png
    - images/touxiang.gif



  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
